# Generated by Django 3.0.6 on 2020-05-15 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('handmade', models.BooleanField()),
                ('production_location', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Packaging',
                'verbose_name_plural': 'Packagings',
            },
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flavor', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tea',
                'verbose_name_plural': 'Teas',
            },
        ),
        migrations.CreateModel(
            name='TeaPackaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longevity_in_months', models.IntegerField()),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaapp.Packaging')),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaapp.Tea')),
            ],
        ),
        migrations.AddField(
            model_name='tea',
            name='packagings',
            field=models.ManyToManyField(through='teaapp.TeaPackaging', to='teaapp.Packaging'),
        ),
        migrations.AddField(
            model_name='packaging',
            name='teas',
            field=models.ManyToManyField(through='teaapp.TeaPackaging', to='teaapp.Tea'),
        ),
    ]
